Repository AY2223S2-CS2113-W13-1/tp, pull requests merged in 2023-03, with the labels that each got.

#25 Medicine class
  src/main/java/seedu/duke/medicine/Medicine.java
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/test/java/seedu/duke/medicine/MedicineManagerTest.java
Labels: medicine

#43 Added a method to allow menu to take in symptoms
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: ui, symptom

#48 fix PR #47
  data/patient-data.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/patient/Patient.java
  src/main/java/seedu/duke/save/Storage.java
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
Labels: bug

#56 Added JUnit test DiagnosisTest.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/seedu/duke/diagnosis/DiagnosisTest.java
Labels: symptom

#57 Revert "Added JUnit test DiagnosisTest.java"
  src/main/java/seedu/duke/Duke.java
  src/test/java/seedu/duke/diagnosis/DiagnosisTest.java
Labels: symptom

#58 Removed redundant lines
  src/test/java/seedu/duke/diagnosis/DiagnosisTest.java
Labels: symptom

#61 Branch brannon 202303071516
  data/patient-data.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/diagnosis/Diagnosis.java
  src/main/java/seedu/duke/diagnosis/IllnessMatch.java
  src/main/java/seedu/duke/diagnosis/illnesses/Illness.java
  src/main/java/seedu/duke/diagnosis/symptoms/Symptom.java
  src/test/java/seedu/duke/diagnosis/DiagnosisTest.java
Labels: symptom

#65 Jeraldchen multiple inputs
  build.gradle
  data/patient-data.txt
  src/main/java/seedu/duke/diagnosis/Diagnosis.java
  src/main/java/seedu/duke/diagnosis/illnesses/bacterial/Bronchitis.java
  src/main/java/seedu/duke/diagnosis/illnesses/psychological/Insomnia.java
  src/main/java/seedu/duke/diagnosis/illnesses/viral/GeneralCold.java
  src/main/java/seedu/duke/diagnosis/illnesses/viral/GeneralFlu.java
  src/main/java/seedu/duke/diagnosis/symptoms/Symptom.java
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/ui/Information.java
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
  src/test/java/seedu/duke/diagnosis/DiagnosisTest.java
Labels: enhancement, priority.High, type.Task

#68 Allow user to see medicine prescription history.
  data/patient-data.txt
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/patient/Patient.java
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
Labels: enhancement, medicine, patient

#73 Branch brannon 202303071516
  data/patient-data.txt
  src/main/java/seedu/duke/diagnosis/illnesses/psychological/Insomnia.java
  src/main/java/seedu/duke/diagnosis/symptoms/Symptom.java
  src/main/java/seedu/duke/patient/Patient.java
  src/main/java/seedu/duke/ui/Menu.java
Labels: ui, symptom

#79 Added diagrams folder.
  docs/diagrams/DiagnosisSequenceDiagram.puml
Labels: documentation

#80 Added documentation and class diagram for DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/DiagnosisClassDiagram.png
  docs/diagrams/DiagnosisClassDiagram.puml
  docs/diagrams/DiagnosisSequenceDiagram.puml
  docs/diagrams/Style.puml
  src/main/java/seedu/duke/diagnosis/Diagnosis.java
Labels: documentation, symptom

#81 Medicine History is now saved.
  data/patient-data.txt
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/diagnosis/Diagnosis.java
  src/main/java/seedu/duke/medicine/Medicine.java
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/patient/Patient.java
  src/main/java/seedu/duke/save/Storage.java
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
  src/test/java/seedu/duke/patient/PatientTest.java
Labels: documentation, enhancement, medicine, storage, patient

#84 Patient UML Diagram
  docs/UserGuide.md
  docs/diagrams/PatientClassDiagram.puml
  src/main/java/seedu/duke/diagnosis/illnesses/Illness.java
  src/main/java/seedu/duke/patient/Patient.java
  src/main/java/seedu/duke/ui/Information.java
  src/main/java/seedu/duke/ui/Menu.java
Labels: documentation

#85 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#96 Fixed bug with medicine file storage
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/save/Storage.java
Labels: bug, medicine, storage

#102 Add list and find features for medicine
  docs/UserGuide.md
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
  src/test/java/seedu/duke/medicine/MedicineManagerTest.java
Labels: enhancement, medicine

#105 Added instructions to UserGuide.md
  docs/UserGuide.md
Labels: documentation

#110 correct DG diagrams
  docs/diagrams/StorageClassDiagram.png
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/loadDataSequenceDiagram.png
  docs/diagrams/loadDataSequenceDiagram.puml
  docs/diagrams/saveDataSequenceDiagram.png
  docs/diagrams/saveDataSequenceDiagram.puml
Labels: documentation, priority.High

#117 Add queue number system and update some medicine descriptions
  data/patient-data.txt
  data/queue_data.txt
  src/main/java/seedu/duke/medicine/Medicine.java
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/patient/Patient.java
  src/main/java/seedu/duke/save/Storage.java
  src/main/java/seedu/duke/ui/Information.java
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
Labels: enhancement

#118 feat: update MedicineManager with more medicines
  data/patient-data.txt
  data/queue_data.txt
  src/main/java/seedu/duke/medicine/MedicineManager.java
Labels: enhancement
