Repository AY2223S2-CS2113-W13-1/tp, pull requests merged in 2023-04, with the labels that each got.

#169 Exit program upon finding corruption
  data/patient-data.txt
  data/queue_data.txt
  docs/diagrams/MenuClassDiagram.png
  docs/diagrams/MenuClassDiagram.puml
  src/main/java/seedu/duke/save/Storage.java
  src/main/java/seedu/duke/ui/Menu.java
Labels: priority.High, storage

#170 Update deleting symptom and other bugs
  data/patient-data.txt
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/main/java/seedu/duke/ui/Information.java
  src/main/java/seedu/duke/ui/Menu.java
  src/main/java/seedu/duke/ui/Parser.java
Labels: enhancement

#172 Updated Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/MedicineSequenceDiagram.png
  docs/diagrams/MedicineSequenceDiagram.puml
  src/main/java/seedu/duke/medicine/Medicine.java
  src/main/java/seedu/duke/medicine/MedicineManager.java
  src/test/java/seedu/duke/medicine/MedicineManagerTest.java
Labels: documentation, medicine, symptom, testing

#175 Fixed diagram formatting
  docs/diagrams/DiagnosisClassDiagram.puml
  docs/diagrams/DiagnosisSequenceDiagram.puml
  docs/diagrams/MedicineSequenceDiagram.puml
  docs/diagrams/PatientClassDiagram.puml
  docs/diagrams/PatientSequenceDiagram.puml
  docs/team/brennanzuz.md
Labels: documentation, invalid

#177 Added link to brennanzuz.md
  docs/AboutUs.md
Labels: documentation, invalid

#185 Add PPP and resolve bugs.
  data/patient-data.txt
  data/queue_data.txt
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/thunderdragon221.md
  src/main/java/seedu/duke/ui/Menu.java
Labels: bug, documentation, priority.High

#188 Introduce more medicines
  data/patient-data.txt
  data/queue_data.txt
  src/main/java/seedu/duke/medicine/MedicineManager.java
Labels: enhancement

#196 Tried to fix image not showing in brennanzuz.md.
  docs/team/brennanzuz.md
Labels: bug, documentation

#197 Tried to fix image not showing in brennanzuz.md.
  docs/team/brennanzuz.md
Labels: bug, documentation
